/**
 * Tests for src/publishing/filter.ts
 *
 * Covers:
 *   - filterFacts: strips private.* keys from facts records
 *   - classifyFact: visibility classification
 *   - sanitizeResponse: PII redaction (emails, phones, API keys)
 *   - isPublicSafe: MemoryEntry public-safety checks
 *   - filterEntries: bulk filtering of MemoryEntry arrays
 *   - filterAndSanitizeFacts: combined filter + sanitize
 */

import { describe, it, expect } from "vitest";
import { PublishingFilter } from "../../src/publishing/filter.js";
import type { MemoryEntry } from "../../src/brain/memory-manager.js";

const filter = new PublishingFilter();

// ─── Helpers ──────────────────────────────────────────────────────────────────

function memoryEntry(overrides: Partial<MemoryEntry> = {}): MemoryEntry {
  return {
    id: "mem-1",
    key: "favorite.color",
    value: "blue",
    type: "explicit",
    confidence: 0.9,
    accessCount: 5,
    lastAccessed: "2026-03-28T00:00:00.000Z",
    createdAt: "2026-03-28T00:00:00.000Z",
    tags: [],
    autoGenerated: false,
    ...overrides,
  };
}

// ─── filterFacts ──────────────────────────────────────────────────────────────

describe("PublishingFilter.filterFacts", () => {
  it("strips all private.* keys", () => {
    const facts = {
      "name": "Alice",
      "private.email": "alice@example.com",
      "private.phone": "555-1234",
      "location": "NYC",
    };
    const result = filter.filterFacts(facts);
    expect(result).toEqual({ name: "Alice", location: "NYC" });
    expect(result).not.toHaveProperty("private.email");
    expect(result).not.toHaveProperty("private.phone");
  });

  it("returns empty object when all keys are private", () => {
    const facts = {
      "private.ssn": "000-00-0000",
      "private.address": "123 Main St",
    };
    expect(filter.filterFacts(facts)).toEqual({});
  });

  it("passes through all public keys unchanged", () => {
    const facts = {
      "name": "Alice",
      "website": "https://alice.dev",
      "bio": "Developer",
    };
    expect(filter.filterFacts(facts)).toEqual(facts);
  });

  it("handles empty facts object", () => {
    expect(filter.filterFacts({})).toEqual({});
  });

  it("does not mutate the input object", () => {
    const facts = { "private.key": "secret", "public.key": "value" };
    const copy = { ...facts };
    filter.filterFacts(facts);
    expect(facts).toEqual(copy);
  });

  it("strips nested private-like keys (private.something.deep)", () => {
    const facts = {
      "private.api.endpoint": "https://api.example.com",
      "public.api.endpoint": "https://public.example.com",
    };
    const result = filter.filterFacts(facts);
    expect(result).toEqual({ "public.api.endpoint": "https://public.example.com" });
  });
});

// ─── classifyFact ─────────────────────────────────────────────────────────────

describe("PublishingFilter.classifyFact", () => {
  it("classifies private.* keys as 'private'", () => {
    expect(filter.classifyFact("private.email")).toBe("private");
    expect(filter.classifyFact("private.ssn")).toBe("private");
  });

  it("classifies sensitive.* keys as 'sensitive'", () => {
    expect(filter.classifyFact("sensitive.token")).toBe("sensitive");
  });

  it("classifies secret.* keys as 'sensitive'", () => {
    expect(filter.classifyFact("secret.key")).toBe("sensitive");
  });

  it("classifies normal keys as 'public'", () => {
    expect(filter.classifyFact("name")).toBe("public");
    expect(filter.classifyFact("favorite.color")).toBe("public");
  });
});

// ─── sanitizeResponse ─────────────────────────────────────────────────────────

describe("PublishingFilter.sanitizeResponse", () => {
  it("redacts email addresses", () => {
    const text = "Contact me at alice@example.com for details";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("alice@example.com");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts multiple emails", () => {
    const text = "alice@example.com and bob@example.org";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("alice@example.com");
    expect(result).not.toContain("bob@example.org");
  });

  it("redacts phone numbers", () => {
    const text = "Call me at 555-123-4567 anytime";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("555-123-4567");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts phone with country code", () => {
    const text = "Reach me at +1 (555) 987-6543";
    const result = filter.sanitizeResponse(text);
    expect(result).toContain("[REDACTED]");
  });

  it("does not redact short digit sequences that are not phone numbers", () => {
    const text = "There are 3 items and 12 others";
    const result = filter.sanitizeResponse(text);
    expect(result).toBe(text);
  });

  it("redacts Stripe-style API keys", () => {
    const text = "Use sk-abc123def456ghi789jkl012mno345pqr for payments";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("sk-abc123def456ghi789jkl012mno345pqr");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts GitHub PATs", () => {
    const text = "Token: ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("ghp_ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefgh");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts AWS access key IDs", () => {
    const text = "Key: AKIAIOSFODNN7EXAMPLE";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("AKIAIOSFODNN7EXAMPLE");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts Bearer tokens", () => {
    const text = "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts Slack tokens", () => {
    const text = "xoxb-TEST-TOKEN-EXAMPLE-NOT-REAL";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("xoxb-TEST-TOKEN-EXAMPLE-NOT-REAL");
    expect(result).toContain("[REDACTED]");
  });

  it("redacts long hex strings (40+ chars)", () => {
    const text = "Secret: abcdef0123456789abcdef0123456789abcdef01";
    const result = filter.sanitizeResponse(text);
    expect(result).toContain("[REDACTED]");
  });

  it("does not redact normal text with no PII", () => {
    const text = "Hello, my name is Alice and I live in New York City.";
    expect(filter.sanitizeResponse(text)).toBe(text);
  });

  it("handles empty string", () => {
    expect(filter.sanitizeResponse("")).toBe("");
  });

  it("redacts multiple PII types in one string", () => {
    const text = "Email: alice@example.com, Phone: 555-123-4567, Key: sk-abc123def456ghi789jkl";
    const result = filter.sanitizeResponse(text);
    expect(result).not.toContain("alice@example.com");
    expect(result).not.toContain("555-123-4567");
    expect(result).not.toContain("sk-abc123def456ghi789jkl");
  });
});

// ─── isPublicSafe ─────────────────────────────────────────────────────────────

describe("PublishingFilter.isPublicSafe", () => {
  it("returns true for explicit entry with no sensitive markers", () => {
    const entry = memoryEntry({ type: "explicit", key: "name", value: "Alice" });
    expect(filter.isPublicSafe(entry)).toBe(true);
  });

  it("returns false for non-explicit types", () => {
    expect(filter.isPublicSafe(memoryEntry({ type: "implicit" }))).toBe(false);
    expect(filter.isPublicSafe(memoryEntry({ type: "error_pattern" }))).toBe(false);
    expect(filter.isPublicSafe(memoryEntry({ type: "preference" }))).toBe(false);
    expect(filter.isPublicSafe(memoryEntry({ type: "task_summary" }))).toBe(false);
  });

  it("returns false for private.* keys", () => {
    const entry = memoryEntry({ type: "explicit", key: "private.email", value: "a@b.com" });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns false for sensitive.* keys", () => {
    const entry = memoryEntry({ type: "explicit", key: "sensitive.token", value: "abc" });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns false for secret.* keys", () => {
    const entry = memoryEntry({ type: "explicit", key: "secret.key", value: "abc" });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns false when entry has 'private' tag", () => {
    const entry = memoryEntry({ type: "explicit", tags: ["private"] });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns false when entry has 'sensitive' tag", () => {
    const entry = memoryEntry({ type: "explicit", tags: ["sensitive"] });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns false when value contains email", () => {
    const entry = memoryEntry({ type: "explicit", value: "Contact: alice@example.com" });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns false when value contains API key", () => {
    const entry = memoryEntry({ type: "explicit", value: "Key: sk-abc123def456ghi789jkl012mno345pqr" });
    expect(filter.isPublicSafe(entry)).toBe(false);
  });

  it("returns true for explicit entry with safe value", () => {
    const entry = memoryEntry({
      type: "explicit",
      key: "bio",
      value: "Software developer based in NYC",
    });
    expect(filter.isPublicSafe(entry)).toBe(true);
  });
});

// ─── filterEntries ────────────────────────────────────────────────────────────

describe("PublishingFilter.filterEntries", () => {
  it("keeps only public-safe entries", () => {
    const entries: MemoryEntry[] = [
      memoryEntry({ id: "1", type: "explicit", key: "name", value: "Alice" }),
      memoryEntry({ id: "2", type: "implicit", key: "name", value: "Alice" }),
      memoryEntry({ id: "3", type: "explicit", key: "private.email", value: "a@b.com" }),
      memoryEntry({ id: "4", type: "explicit", key: "bio", value: "Developer" }),
    ];
    const result = filter.filterEntries(entries);
    expect(result).toHaveLength(2);
    expect(result.map((e) => e.id)).toEqual(["1", "4"]);
  });

  it("returns empty array when no entries are safe", () => {
    const entries: MemoryEntry[] = [
      memoryEntry({ type: "implicit" }),
      memoryEntry({ type: "explicit", key: "private.x", value: "y" }),
    ];
    expect(filter.filterEntries(entries)).toHaveLength(0);
  });

  it("returns empty array for empty input", () => {
    expect(filter.filterEntries([])).toHaveLength(0);
  });
});

// ─── filterAndSanitizeFacts ───────────────────────────────────────────────────

describe("PublishingFilter.filterAndSanitizeFacts", () => {
  it("strips private keys and sanitizes values", () => {
    const facts = {
      "name": "Alice",
      "private.email": "alice@example.com",
      "contact": "Call me at 555-123-4567",
    };
    const result = filter.filterAndSanitizeFacts(facts);
    expect(result).not.toHaveProperty("private.email");
    expect(result["name"]).toBe("Alice");
    expect(result["contact"]).not.toContain("555-123-4567");
    expect(result["contact"]).toContain("[REDACTED]");
  });

  it("passes through clean public facts unchanged", () => {
    const facts = { "name": "Alice", "location": "NYC" };
    expect(filter.filterAndSanitizeFacts(facts)).toEqual(facts);
  });

  it("handles empty input", () => {
    expect(filter.filterAndSanitizeFacts({})).toEqual({});
  });
});
