/**
 * StatusAPI — real-time agent health and metrics dashboard endpoints.
 *
 * Registers HTTP routes on the existing BridgeServer peer API:
 *   GET /api/status        — full agent overview (agent, brain, llm, fleet, system)
 *   GET /api/status/memory — detailed memory stats (facts by category, timeline, wiki, knowledge)
 *   GET /api/status/fleet  — fleet peer status (connected peers, heartbeats, pending messages)
 */

import type { IncomingMessage, ServerResponse } from "http";
import type { Brain } from "../brain/index.js";
import type { TokenTracker, TokenStats } from "../metrics/token-tracker.js";
import type { BridgeConfig } from "../config/types.js";
import type { FleetAgent } from "../fleet/agent.js";
import { execSync } from "child_process";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface StatusDependencies {
  brain: Brain | undefined;
  tokenTracker: TokenTracker | undefined;
  config: BridgeConfig;
  repoRoot: string;
  fleetAgent: FleetAgent | undefined;
  startTime: number;
}

export interface AgentStatus {
  name: string;
  version: string;
  mode: string;
  uptime: number;
  repoRoot: string;
}

export interface BrainStatus {
  facts: number;
  memories: number;
  wikiPages: number;
  knowledgeEntries: number;
  lastSync: string | null;
}

export interface LLMStatus {
  provider: string;
  model: string;
  requestsToday: number;
  tokensToday: number;
  avgLatency: number;
}

export interface FleetStatus {
  peers: number;
  messagesSent: number;
  messagesReceived: number;
}

export interface SystemStatus {
  memoryUsage: string;
  cpuPercent: number;
  diskUsage: string;
}

export interface StatusResponse {
  agent: AgentStatus;
  brain: BrainStatus;
  llm: LLMStatus;
  fleet: FleetStatus;
  system: SystemStatus;
}

export interface MemoryDetailResponse {
  factsByCategory: Record<string, number>;
  memoryTimeline: Array<{ date: string; added: number; total: number }>;
  wikiPages: Array<{ file: string; title: string }>;
  knowledgeByType: Record<string, number>;
  memoryStats: {
    total: number;
    autoGenerated: number;
    avgConfidence: number;
    types: Record<string, number>;
  } | null;
}

export interface FleetDetailResponse {
  connectedPeers: Array<{
    agentId: string;
    agentName: string;
    status: string;
    lastHeartbeat: string | null;
    skills: string[];
  }>;
  pendingMessages: number;
  role: string | null;
  fleetId: string | null;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(1)}GB`;
}

function getDiskUsage(repoRoot: string): string {
  try {
    const stats = execSync(`du -sb "${repoRoot}" 2>/dev/null | cut -f1`, {
      encoding: "utf-8",
      timeout: 3000,
    }).trim();
    return formatBytes(parseInt(stats, 10) || 0);
  } catch {
    return "unknown";
  }
}

function categorizeFacts(facts: Record<string, string>): Record<string, number> {
  const categories: Record<string, number> = {};
  for (const key of Object.keys(facts)) {
    const prefix = key.split(".")[0] || "other";
    categories[prefix] = (categories[prefix] || 0) + 1;
  }
  return categories;
}

function getMemoryTimeline(
  memories: Array<{ createdAt: string }>
): Array<{ date: string; added: number; total: number }> {
  const now = new Date();
  const timeline: Array<{ date: string; added: number; total: number }> = [];

  for (let i = 6; i >= 0; i--) {
    const day = new Date(now);
    day.setDate(day.getDate() - i);
    day.setHours(0, 0, 0, 0);
    const nextDay = new Date(day);
    nextDay.setDate(nextDay.getDate() + 1);

    const dayStr = day.toISOString().slice(0, 10);
    const added = memories.filter((m) => {
      const t = new Date(m.createdAt).getTime();
      return t >= day.getTime() && t < nextDay.getTime();
    }).length;

    // Total is cumulative up to end of this day
    const total = memories.filter((m) =>
      new Date(m.createdAt).getTime() < nextDay.getTime()
    ).length;

    timeline.push({ date: dayStr, added, total });
  }

  return timeline;
}

// ─── StatusAPI ────────────────────────────────────────────────────────────────

export class StatusAPI {
  private deps: StatusDependencies;

  constructor(deps: StatusDependencies) {
    this.deps = deps;
  }

  /**
   * Route an incoming HTTP request to the appropriate status handler.
   * Returns true if the request was handled, false otherwise.
   */
  async handleRequest(
    req: IncomingMessage,
    res: ServerResponse
  ): Promise<boolean> {
    const url = req.url || "";

    if (url === "/api/status" && req.method === "GET") {
      return this.handleStatus(req, res);
    }

    if (url === "/api/status/memory" && req.method === "GET") {
      return this.handleMemory(req, res);
    }

    if (url === "/api/status/fleet" && req.method === "GET") {
      return this.handleFleet(req, res);
    }

    return false;
  }

  // ---------------------------------------------------------------------------
  // GET /api/status
  // ---------------------------------------------------------------------------

  private async handleStatus(
    _req: IncomingMessage,
    res: ServerResponse
  ): Promise<boolean> {
    const body = this.buildStatusResponse();
    this.json(res, 200, body);
    return true;
  }

  buildStatusResponse(): StatusResponse {
    return {
      agent: this.getAgentStatus(),
      brain: this.getBrainStatus(),
      llm: this.getLLMStatus(),
      fleet: this.getFleetStatus(),
      system: this.getSystemStatus(),
    };
  }

  // ---------------------------------------------------------------------------
  // GET /api/status/memory
  // ---------------------------------------------------------------------------

  private async handleMemory(
    _req: IncomingMessage,
    res: ServerResponse
  ): Promise<boolean> {
    const body = this.buildMemoryDetail();
    this.json(res, 200, body);
    return true;
  }

  buildMemoryDetail(): MemoryDetailResponse {
    const { brain } = this.deps;

    // Facts
    const facts = brain?.getAllFacts("private") ?? {};
    const factsByCategory = categorizeFacts(facts);

    // Memories
    const memories = brain?.getMemories({ mode: "private" }) ?? [];
    const memoryTimeline = getMemoryTimeline(memories);
    const memoryStats = brain?.memoryManager?.stats() ?? null;

    // Wiki pages
    const wikiPages = (brain?.listWikiPages() ?? []).map((p) => ({
      file: p.file,
      title: p.title,
    }));

    // Knowledge entries — approximate from brain facts
    const knowledgeByType: Record<string, number> = {};
    for (const key of Object.keys(facts)) {
      if (key.startsWith("knowledge.")) {
        const type = key.split(".")[1] || "unknown";
        knowledgeByType[type] = (knowledgeByType[type] || 0) + 1;
      }
    }

    return {
      factsByCategory,
      memoryTimeline,
      wikiPages,
      knowledgeByType,
      memoryStats,
    };
  }

  // ---------------------------------------------------------------------------
  // GET /api/status/fleet
  // ---------------------------------------------------------------------------

  private async handleFleet(
    _req: IncomingMessage,
    res: ServerResponse
  ): Promise<boolean> {
    const body = await this.buildFleetDetail();
    this.json(res, 200, body);
    return true;
  }

  async buildFleetDetail(): Promise<FleetDetailResponse> {
    const { fleetAgent } = this.deps;

    if (!fleetAgent) {
      return {
        connectedPeers: [],
        pendingMessages: 0,
        role: null,
        fleetId: null,
      };
    }

    let agents: Array<{
      agentId: string;
      agentName: string;
      status: string;
      lastHeartbeat: number | null;
      skills: string[];
    }> = [];

    try {
      const fleetAgents = await fleetAgent.listAgents();
      agents = fleetAgents.map((a) => ({
        agentId: a.id,
        agentName: a.name,
        status: a.status,
        lastHeartbeat: a.lastHeartbeat ?? null,
        skills: a.skills ?? [],
      }));
    } catch {
      // listAgents() only works for leaders; workers return empty
    }

    return {
      connectedPeers: agents,
      pendingMessages: 0,
      role: fleetAgent.getRole(),
      fleetId: fleetAgent.getFleetId(),
    };
  }

  // ---------------------------------------------------------------------------
  // Status builders (public for testing)
  // ---------------------------------------------------------------------------

  getAgentStatus(): AgentStatus {
    const agentName =
      this.deps.brain?.getFact("agent.name") ?? "Cocapn Agent";
    return {
      name: agentName,
      version: "0.2.0",
      mode: this.deps.config.config.mode,
      uptime: Math.floor((Date.now() - this.deps.startTime) / 1000),
      repoRoot: this.deps.repoRoot,
    };
  }

  getBrainStatus(): BrainStatus {
    const { brain } = this.deps;
    const facts = brain?.getAllFacts("private") ?? {};
    const memories = brain?.getMemories({ mode: "private" }) ?? [];
    const wikiPages = brain?.listWikiPages() ?? [];

    // Knowledge entries count from facts
    let knowledgeEntries = 0;
    for (const key of Object.keys(facts)) {
      if (key.startsWith("knowledge.")) knowledgeEntries++;
    }

    return {
      facts: Object.keys(facts).length,
      memories: memories.length,
      wikiPages: wikiPages.length,
      knowledgeEntries,
      lastSync: this.getLastSyncTime(),
    };
  }

  getLLMStatus(): LLMStatus {
    const { tokenTracker, config } = this.deps;
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const stats: TokenStats = tokenTracker?.getStats(today) ?? {
      totalTokensIn: 0,
      totalTokensOut: 0,
      totalTokens: 0,
      avgTokensPerTask: 0,
      tasksCompleted: 0,
      tasksFailed: 0,
      tokensByModule: {},
      tokensBySkill: {},
      tokensByTask: {},
      efficiency: 0,
      topWasters: [],
      period: { start: today.toISOString(), end: new Date().toISOString() },
    };

    const provider = config.llm?.providers
      ? Object.keys(config.llm.providers)[0] ?? "none"
      : "none";

    const model = config.llm?.defaultModel ?? "none";

    return {
      provider,
      model,
      requestsToday: stats.tasksCompleted + stats.tasksFailed,
      tokensToday: stats.totalTokens,
      avgLatency:
        stats.tasksCompleted > 0
          ? Math.round(stats.totalTokens / stats.tasksCompleted)
          : 0,
    };
  }

  getFleetStatus(): FleetStatus {
    const { fleetAgent } = this.deps;

    if (!fleetAgent) {
      return { peers: 0, messagesSent: 0, messagesReceived: 0 };
    }

    // FleetAgent doesn't expose message counts publicly — use 0
    return {
      peers: 0, // populated asynchronously via listAgents()
      messagesSent: 0,
      messagesReceived: 0,
    };
  }

  getSystemStatus(): SystemStatus {
    const mem = process.memoryUsage();
    const rssMB = formatBytes(mem.rss);

    let cpuPercent = 0;
    try {
      const load = process.cpuUsage();
      // Normalize to percentage (approximate, based on 1s wall time)
      cpuPercent = Math.min(
        100,
        Math.round(((load.user + load.system) / 1e6 / process.uptime()) * 100)
      );
    } catch {
      // CPU usage unavailable
    }

    return {
      memoryUsage: rssMB,
      cpuPercent,
      diskUsage: getDiskUsage(this.deps.repoRoot),
    };
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  private getLastSyncTime(): string | null {
    const { brain } = this.deps;
    if (!brain) return null;
    const lastSync = brain.getFact("system.lastSync", "private");
    return lastSync ?? null;
  }

  private json(res: ServerResponse, code: number, body: unknown): void {
    res.writeHead(code, { "Content-Type": "application/json" });
    res.end(JSON.stringify(body, null, 2));
  }
}
